{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.torlando-tech",
    "module" : "LXST-kt",
    "version" : "v0.0.8",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "9.4.1"
    }
  },
  "variants" : [ {
    "name" : "releaseVariantReleaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "2.2.10"
      }
    } ],
    "files" : [ {
      "name" : "LXST-kt-v0.0.8.aar",
      "url" : "LXST-kt-v0.0.8.aar",
      "size" : 3149492,
      "sha512" : "87ed265114cfaf969b67d7d3c98f5addc9f8cd4a56e2ea6a2c352790e278bae53a027ed85a9bc28ec675c6c77224ae617ba1209617be9ddf10503f249c47f46b",
      "sha256" : "a6e1c000e62484b1f150d06df83b653974474c7d0d6bab834627b21182b8db2d",
      "sha1" : "19ade1480398e4d34ab355e8715f5449b9c97a1c",
      "md5" : "0eeb10766eda6900a1e75452cc59abc6"
    } ]
  }, {
    "name" : "releaseVariantReleaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "com.google.oboe",
      "module" : "oboe",
      "version" : {
        "requires" : "1.9.0"
      }
    }, {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-core",
      "version" : {
        "requires" : "1.10.2"
      }
    }, {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-android",
      "version" : {
        "requires" : "1.10.2"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "2.2.10"
      }
    } ],
    "files" : [ {
      "name" : "LXST-kt-v0.0.8.aar",
      "url" : "LXST-kt-v0.0.8.aar",
      "size" : 3149492,
      "sha512" : "87ed265114cfaf969b67d7d3c98f5addc9f8cd4a56e2ea6a2c352790e278bae53a027ed85a9bc28ec675c6c77224ae617ba1209617be9ddf10503f249c47f46b",
      "sha256" : "a6e1c000e62484b1f150d06df83b653974474c7d0d6bab834627b21182b8db2d",
      "sha1" : "19ade1480398e4d34ab355e8715f5449b9c97a1c",
      "md5" : "0eeb10766eda6900a1e75452cc59abc6"
    } ]
  }, {
    "name" : "releaseVariantReleaseSourcePublication",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "LXST-kt-v0.0.8.jar",
      "url" : "LXST-kt-v0.0.8.jar",
      "size" : 88818,
      "sha512" : "0ac2127d3b557a69e1023a48ad5079dac0285eea501d41f685fbb81554f4fe7678bc5cd6c8f5b17e58ef6f64045288e64147fe74e2e5c779cefdabb5c2dffc68",
      "sha256" : "852f46cc69937119766947e7a256b978b2147699b699cdcf37b375d5713dcd62",
      "sha1" : "9382f5f5ea18ec90da18a677d70d5cfa7e4dcea8",
      "md5" : "2e403fc4fe2a32bf3308c472acc989a2"
    } ]
  } ]
}