{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.torlando-tech",
    "module" : "LXMF-kt",
    "version" : "v0.0.14",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "8.5"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "21",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "dependencies" : [ {
      "group" : "com.github.torlando-tech.reticulum-kt",
      "module" : "rns-core",
      "version" : {
        "requires" : "v0.0.22"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "2.3.0"
      }
    } ],
    "files" : [ {
      "name" : "LXMF-kt-v0.0.14.jar",
      "url" : "LXMF-kt-v0.0.14.jar",
      "size" : 131134,
      "sha512" : "0720f2cfc72538361ba429d26bd10391f8dfd3f6172f042ac1efccf0bc16ca70890c566884d8d67fe5d5e89ec58801cbabf0cc6cd5b553faedce07bd7843a127",
      "sha256" : "127af16253d63caeb50a6b49a9f84ef642b7eec28dcbfd4a11a36ac981e00c5d",
      "sha1" : "b82b8f594625ec395b01e25c073b3d25192a4bb8",
      "md5" : "ec58acf78739cff6b071109333ad907e"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "21",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-core",
      "version" : {
        "requires" : "1.8.0"
      }
    }, {
      "group" : "org.msgpack",
      "module" : "msgpack-core",
      "version" : {
        "requires" : "0.9.8"
      }
    }, {
      "group" : "io.github.microutils",
      "module" : "kotlin-logging-jvm",
      "version" : {
        "requires" : "3.0.5"
      }
    }, {
      "group" : "com.github.torlando-tech.reticulum-kt",
      "module" : "rns-core",
      "version" : {
        "requires" : "v0.0.22"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "2.3.0"
      }
    } ],
    "files" : [ {
      "name" : "LXMF-kt-v0.0.14.jar",
      "url" : "LXMF-kt-v0.0.14.jar",
      "size" : 131134,
      "sha512" : "0720f2cfc72538361ba429d26bd10391f8dfd3f6172f042ac1efccf0bc16ca70890c566884d8d67fe5d5e89ec58801cbabf0cc6cd5b553faedce07bd7843a127",
      "sha256" : "127af16253d63caeb50a6b49a9f84ef642b7eec28dcbfd4a11a36ac981e00c5d",
      "sha1" : "b82b8f594625ec395b01e25c073b3d25192a4bb8",
      "md5" : "ec58acf78739cff6b071109333ad907e"
    } ]
  }, {
    "name" : "sourcesElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "LXMF-kt-v0.0.14.jar",
      "url" : "LXMF-kt-v0.0.14.jar",
      "size" : 46162,
      "sha512" : "2a02b89fc8465f0ac4a1eaaa43d9f02170bdfa859d3321e83aabf3761f88299b9672807a81f682650588f2f25bfbbb4a89a6d7fed866e606591ec782324d10ed",
      "sha256" : "7aaaa0f27ab14628424994158ce01a9a91454dc85af6ef95f50625dd00bb5b54",
      "sha1" : "9cc743a353ce16ca0ac7170f79846a0c19e437bb",
      "md5" : "522207d10056331b42c71a6d2ea8aa0f"
    } ]
  } ]
}