{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.torlando-tech",
    "module" : "reticulum-kt",
    "version" : "v0.0.22",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "9.4.1"
    }
  },
  "variants" : [ {
    "name" : "releaseVariantReleaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "dependencies" : [ {
      "group" : "com.github.torlando-tech.reticulum-kt",
      "module" : "rns-core",
      "version" : {
        "requires" : "v0.0.22"
      }
    }, {
      "group" : "com.github.torlando-tech.reticulum-kt",
      "module" : "rns-interfaces",
      "version" : {
        "requires" : "v0.0.22"
      }
    }, {
      "group" : "androidx.lifecycle",
      "module" : "lifecycle-service",
      "version" : {
        "requires" : "2.7.0"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "2.3.0"
      }
    } ],
    "files" : [ {
      "name" : "rns-android-v0.0.22.aar",
      "url" : "rns-android-v0.0.22.aar",
      "size" : 574308,
      "sha512" : "3c6d75d45d947293c7e8611e8a4c7b052a502ebc530431959acdb00e619fdc086b67d8e1e6144b7c38c7b377ed5239a7589600b14120d716a62119e367d97750",
      "sha256" : "efea96f9eaffb9be593eaaa9d33e697432a72b18caf8e57a8736aceb3ac55e89",
      "sha1" : "9cc3bb87037fc16c9ac371b710ad842928f44de9",
      "md5" : "bfd78894f77c7241eb2ce850b8e2e1d6"
    } ]
  }, {
    "name" : "releaseVariantReleaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-parcelize-runtime",
      "version" : {
        "requires" : "2.3.0"
      }
    }, {
      "group" : "androidx.core",
      "module" : "core-ktx",
      "version" : {
        "requires" : "1.12.0"
      }
    }, {
      "group" : "androidx.lifecycle",
      "module" : "lifecycle-runtime-ktx",
      "version" : {
        "requires" : "2.7.0"
      }
    }, {
      "group" : "androidx.work",
      "module" : "work-runtime-ktx",
      "version" : {
        "requires" : "2.9.0"
      }
    }, {
      "group" : "com.google.android.gms",
      "module" : "play-services-nearby",
      "version" : {
        "requires" : "19.3.0"
      }
    }, {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-android",
      "version" : {
        "requires" : "1.8.0"
      }
    }, {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-play-services",
      "version" : {
        "requires" : "1.8.0"
      }
    }, {
      "group" : "androidx.room",
      "module" : "room-runtime",
      "version" : {
        "requires" : "2.6.1"
      }
    }, {
      "group" : "androidx.room",
      "module" : "room-ktx",
      "version" : {
        "requires" : "2.6.1"
      }
    }, {
      "group" : "com.github.torlando-tech.reticulum-kt",
      "module" : "rns-core",
      "version" : {
        "requires" : "v0.0.22"
      }
    }, {
      "group" : "com.github.torlando-tech.reticulum-kt",
      "module" : "rns-interfaces",
      "version" : {
        "requires" : "v0.0.22"
      }
    }, {
      "group" : "androidx.lifecycle",
      "module" : "lifecycle-service",
      "version" : {
        "requires" : "2.7.0"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "2.3.0"
      }
    } ],
    "files" : [ {
      "name" : "rns-android-v0.0.22.aar",
      "url" : "rns-android-v0.0.22.aar",
      "size" : 574308,
      "sha512" : "3c6d75d45d947293c7e8611e8a4c7b052a502ebc530431959acdb00e619fdc086b67d8e1e6144b7c38c7b377ed5239a7589600b14120d716a62119e367d97750",
      "sha256" : "efea96f9eaffb9be593eaaa9d33e697432a72b18caf8e57a8736aceb3ac55e89",
      "sha1" : "9cc3bb87037fc16c9ac371b710ad842928f44de9",
      "md5" : "bfd78894f77c7241eb2ce850b8e2e1d6"
    } ]
  }, {
    "name" : "releaseVariantReleaseSourcePublication",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "rns-android-v0.0.22.jar",
      "url" : "rns-android-v0.0.22.jar",
      "size" : 120269,
      "sha512" : "251f7cb0ea3b984a653b9e45d2146f48b910966faba8d2b8a688bda5de6ad9bf315dea26748409fba4c5b17ce12127529faa67d5275383ee42bf5a6179f80fd3",
      "sha256" : "cbb702df3fc6fbe4ebec6149a488b6b6683172741a1a4c548732d2fc64c31f0f",
      "sha1" : "45de9062959dec2b3db0fb7313d87701bc107848",
      "md5" : "590a12280e9fc02cec5f84b5fb45bbb4"
    } ]
  } ]
}