{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.torlando-tech",
    "module" : "reticulum-kt",
    "version" : "v0.0.22",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "9.4.1"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "21",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "dependencies" : [ {
      "group" : "com.github.torlando-tech.reticulum-kt",
      "module" : "rns-core",
      "version" : {
        "requires" : "v0.0.22"
      }
    }, {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-core",
      "version" : {
        "requires" : "1.8.0"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "2.3.0"
      }
    } ],
    "files" : [ {
      "name" : "rns-interfaces-v0.0.22.jar",
      "url" : "rns-interfaces-v0.0.22.jar",
      "size" : 479415,
      "sha512" : "c76edc955b673086995ea4a13426c7fe2dacfbbed379b99db0843ea8fd2f9556995a35bc50f64892c1dc6288b2452ce20b8d968115eb13a86e6aec18d2d7d0f8",
      "sha256" : "ba4747668e20cc0c978d975f37e8429f61901c13c1989baca42b2372beaf688d",
      "sha1" : "c8d08649899a31b9bd8e7aac8467b39f7f3366fc",
      "md5" : "cbd69c9f3823b9d848c4484690719114"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "21",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "dependencies" : [ {
      "group" : "com.github.torlando-tech.reticulum-kt",
      "module" : "rns-core",
      "version" : {
        "requires" : "v0.0.22"
      }
    }, {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-core",
      "version" : {
        "requires" : "1.8.0"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "2.3.0"
      }
    } ],
    "files" : [ {
      "name" : "rns-interfaces-v0.0.22.jar",
      "url" : "rns-interfaces-v0.0.22.jar",
      "size" : 479415,
      "sha512" : "c76edc955b673086995ea4a13426c7fe2dacfbbed379b99db0843ea8fd2f9556995a35bc50f64892c1dc6288b2452ce20b8d968115eb13a86e6aec18d2d7d0f8",
      "sha256" : "ba4747668e20cc0c978d975f37e8429f61901c13c1989baca42b2372beaf688d",
      "sha1" : "c8d08649899a31b9bd8e7aac8467b39f7f3366fc",
      "md5" : "cbd69c9f3823b9d848c4484690719114"
    } ]
  }, {
    "name" : "sourcesElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "rns-interfaces-v0.0.22.jar",
      "url" : "rns-interfaces-v0.0.22.jar",
      "size" : 111236,
      "sha512" : "43e6db332e5692aeb20994dc6d1693a8d692ffd98d38391a857d9c8a7abf673bad2492843b9b5c7e32d733259ab78bc987afca633d35c6747a2cf0164536db49",
      "sha256" : "f3d1d053a13bc1d9aa72a6c57778e45cd3e718cd4cd4a40330f72af2c42826aa",
      "sha1" : "4837913126d6e20860acd13c1accbcee33d0411f",
      "md5" : "1779c97ed1de5b4b7806c0d807c8b602"
    } ]
  } ]
}